'use client';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
type User={id:string;email:string;name:string;role:'admin'|'doctor'|'patient'};
type Doctor={id:number;name:string;email?:string;specialty:string;location:string;qualification:string;price:number};
type Slot={id:number;startsAt:string;doctorId:number};
type Booking={id:number;startsAt:string;doctorName:string;specialty:string;location:string};
type Appointment={id:number;startsAt:string;patientName:string};
const labels={admin:'لوحة الإدارة',doctor:'لوحة الطبيب',patient:'لوحة المريض'};
const date=(value:string)=>new Intl.DateTimeFormat('ar-EG',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
async function request<T>(url:string, method='GET', body?:object):Promise<T>{const res=await fetch(url,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'حدث خطأ، حاول مرة أخرى');return data as T;}
export default function Dashboard(){
 const [user,setUser]=useState<User|null>(null),[doctors,setDoctors]=useState<Doctor[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[appointments,setAppointments]=useState<Appointment[]>([]),[slots,setSlots]=useState<Slot[]>([]),[selected,setSelected]=useState<Doctor|null>(null),[search,setSearch]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const refresh=useCallback(async()=>{const {user:u}=await request<{user:User|null}>('/api/session');setUser(u);if(!u)return;const {doctors:d}=await request<{doctors:Doctor[]}>(u.role==='admin'?'/api/admin/doctors':'/api/doctors');setDoctors(d);if(u.role==='patient'){const b=await request<{bookings:Booking[]}>('/api/bookings');setBookings(b.bookings);}if(u.role==='doctor'){const a=await request<{appointments:Appointment[]}>('/api/doctor/appointments');setAppointments(a.appointments);}},[]);
 useEffect(()=>{refresh().catch(e=>setMessage(e.message)).finally(()=>setLoading(false));},[refresh]);
 async function run(action:()=>Promise<void>){setBusy(true);setMessage('');try{await action();await refresh();}catch(e){setMessage(e instanceof Error?e.message:'حدث خطأ');}finally{setBusy(false);}}
 async function choose(d:Doctor){setSelected(d);setMessage('');try{const data=await request<{slots:Slot[]}>(`/api/slots?doctorId=${d.id}`);setSlots(data.slots);}catch(e){setMessage(e instanceof Error?e.message:'تعذر تحميل المواعيد');}}
 async function addDoctor(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form).entries());await run(async()=>{await request('/api/admin/doctors','POST',{...data,price:Number(data.price)});form.reset();setMessage('تمت إضافة الطبيب. يمكنه الدخول بنفس البريد الإلكتروني.');});}
 async function addSlot(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const value=String(new FormData(form).get('startsAt')||'');await run(async()=>{await request('/api/slots','POST',{startsAt:new Date(value).toISOString()});form.reset();setMessage('تمت إضافة الموعد.');});}
 const filtered=doctors.filter(d=>`${d.name} ${d.specialty} ${d.location}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="/">✚ <span>Clin<span className="accent">IQ</span></span></a><div className="side-label">مساحة العمل</div><a className="side-active" href="#overview">◫ &nbsp; {user?labels[user.role]:'الرئيسية'}</a>{user?.role==='patient'&&<><a href="#doctors">♧ &nbsp; ابحث عن طبيب</a><a href="#bookings">◷ &nbsp; مواعيدي</a></>}{user?.role==='admin'&&<><a href="#add">✚ &nbsp; إضافة طبيب</a><a href="#doctors">♧ &nbsp; الأطباء</a></>}{user?.role==='doctor'&&<><a href="#add">✚ &nbsp; إضافة موعد</a><a href="#appointments">◷ &nbsp; الحجوزات</a></>}<div className="sidebar-bottom"><span>● النظام متصل</span><a href="/signout-with-chatgpt?return_to=%2F" target="_top">تسجيل الخروج ↗</a></div></aside><main className="main"><header className="topbar"><span>منصة ClinIQ / {user?labels[user.role]:'الحساب'}</span><div className="user-chip">◉ &nbsp; {user?.name||'جار التحميل...'}</div></header><div className="content" id="overview">{loading?<div className="panel">جار تحميل بياناتك...</div>:!user?<div className="panel">تعذر تحميل الحساب. <a href="/signin-with-chatgpt?return_to=%2F" target="_top">سجل الدخول مجددًا</a></div>:<><div className="welcome"><div><span className="eyebrow">CLINIQ / {labels[user.role]}</span><h1>أهلًا، {user.name.split(' ')[0]} <span className="wave">✳</span></h1><p>{user.role==='admin'?'أضف الأطباء ونظم بيانات المنصة من هنا.':user.role==='doctor'?'نظم أوقاتك واطلع على الحجوزات القادمة.':'اكتشف الأطباء واحجز الموعد المناسب لك.'}</p></div><span className="role-badge">{user.role==='admin'?'مدير المنصة':user.role==='doctor'?'طبيب':'مريض'}</span></div>{message&&<div className="notice" role="status">{message} <button onClick={()=>setMessage('')} aria-label="إغلاق">×</button></div>}
{user.role==='admin'&&<><section className="summary-row"><div className="stat"><small>الأطباء على المنصة</small><strong>{doctors.length}</strong><span>طبيب مضاف</span></div><div className="stat pale"><small>نوع الحساب</small><strong>مدير</strong><span>لديك صلاحية إضافة الأطباء</span></div></section><section className="panel" id="add"><div className="section-heading"><div><span className="eyebrow">إدارة الفريق الطبي</span><h2>إضافة طبيب جديد</h2></div></div><p className="muted">أدخل بيانات الطبيب والبريد الذي سيستخدمه للدخول بحساب ChatGPT. سيظهر مباشرة في قائمة الأطباء.</p><form className="form-grid" onSubmit={addDoctor}><label>اسم الطبيب<input required name="name" maxLength={150} placeholder="د. أحمد محمد" /></label><label>البريد الإلكتروني<input required type="email" name="email" placeholder="doctor@example.com" /></label><label>التخصص<input required name="specialty" maxLength={100} placeholder="طب القلب" /></label><label>الموقع<input required name="location" maxLength={200} placeholder="القاهرة، مصر" /></label><label>سعر الكشف<input required type="number" name="price" min="0" max="100000" placeholder="500" /></label><label>المؤهل العلمي<input name="qualification" maxLength={500} placeholder="اختياري" /></label><button className="primary" disabled={busy}>+ إضافة الطبيب</button></form></section><section id="doctors" className="panel"><div className="section-heading"><div><span className="eyebrow">دليل الفريق</span><h2>الأطباء المسجلون</h2></div><span className="count">{doctors.length} طبيب</span></div>{doctors.length?<div className="list">{doctors.map(d=><div className="list-item" key={d.id}><div className="avatar">✚</div><div><strong>{d.name}</strong><p>{d.specialty} · {d.location}</p><small>{d.email}</small></div><span className="price">{d.price} ج.م</span></div>)}</div>:<div className="empty">لم تضف أي طبيب بعد. ابدأ من النموذج بالأعلى.</div>}</section></>}
{user.role==='patient'&&<><section className="summary-row"><div className="stat"><small>الأطباء المتاحون</small><strong>{doctors.length}</strong><span>اختر التخصص المناسب</span></div><div className="stat pale"><small>حجوزاتي</small><strong>{bookings.length}</strong><span>يمكنك إدارة مواعيدك</span></div></section><section id="doctors" className="panel"><div className="section-heading"><div><span className="eyebrow">دليل الأطباء</span><h2>اعثر على الطبيب المناسب</h2></div><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث بالاسم أو التخصص أو المدينة..." aria-label="البحث عن طبيب"/></div>{filtered.length?<div className="doctor-grid">{filtered.map(d=><article className="doctor-card" key={d.id}><div className="avatar large">✚</div><span className="tag">{d.specialty}</span><h3>{d.name}</h3><p>{d.qualification||'طبيب على منصة ClinIQ'}</p><div className="doctor-meta">⌖ {d.location} <strong>{d.price} ج.م</strong></div><button className="secondary" onClick={()=>choose(d)}>عرض المواعيد ←</button></article>)}</div>:<div className="empty">لا يوجد أطباء مطابقون الآن.</div>}</section>{selected&&<section className="panel"><div className="section-heading"><div><span className="eyebrow">مواعيد متاحة</span><h2>مواعيد {selected.name}</h2></div><button className="text-button" onClick={()=>setSelected(null)}>إغلاق ×</button></div>{slots.length?<div className="slots">{slots.map(s=><button disabled={busy} key={s.id} onClick={()=>run(async()=>{await request('/api/bookings','POST',{slotId:s.id});await choose(selected);setMessage('تم تأكيد الحجز بنجاح.');})}>{date(s.startsAt)} <span>احجز ←</span></button>)}</div>:<div className="empty">لا توجد مواعيد متاحة لهذا الطبيب حاليًا.</div>}</section>}<section id="bookings" className="panel"><div className="section-heading"><div><span className="eyebrow">المواعيد</span><h2>حجوزاتي</h2></div></div>{bookings.length?<div className="list">{bookings.map(b=><div key={b.id} className="list-item"><div className="avatar">◷</div><div><strong>{b.doctorName}</strong><p>{b.specialty} · {b.location}</p><small>{date(b.startsAt)}</small></div>{new Date(b.startsAt)>new Date()&&<button className="danger" disabled={busy} onClick={()=>run(async()=>{await request('/api/bookings/cancel','POST',{slotId:b.id});setMessage('تم إلغاء الحجز.');})}>إلغاء</button>}</div>)}</div>:<div className="empty">لم تحجز موعدًا بعد. ابحث عن طبيب وابدأ رحلتك.</div>}</section></>}
{user.role==='doctor'&&<><section id="add" className="panel"><div className="section-heading"><div><span className="eyebrow">جدول المواعيد</span><h2>أضف موعدًا متاحًا</h2></div></div><p className="muted">اختر تاريخًا ووقتًا مناسبين لمرضى العيادة.</p><form className="inline-form" onSubmit={addSlot}><label>التاريخ والوقت<input required type="datetime-local" name="startsAt" /></label><button className="primary" disabled={busy}>+ إضافة الموعد</button></form></section><section id="appointments" className="panel"><div className="section-heading"><div><span className="eyebrow">المرضى</span><h2>الحجوزات المسجلة</h2></div><span className="count">{appointments.length} حجز</span></div>{appointments.length?<div className="list">{appointments.map(a=><div className="list-item" key={a.id}><div className="avatar">◷</div><div><strong>{a.patientName}</strong><p>{date(a.startsAt)}</p></div></div>)}</div>:<div className="empty">لا توجد حجوزات حتى الآن. أضف مواعيد ليتمكن المرضى من الحجز.</div>}</section></>}
<footer>© {new Date().getFullYear()} ClinIQ · لحالات الطوارئ، اتصل بخدمات الطوارئ المحلية.</footer></>}</div></main></div>;
}
